### PR TITLE
feat: integrate legal component to sdk release

### PR DESCRIPTION
**Pull request by RatnadeepSimhadri**
This PR is to Integrate `legal-component` into `sdk-release`
**Tests and Code Coverage for `Legal Component`**

**Spec PR**
https://github.com/paypal/paypal-sdk-spec/pull/86

**Component Core Logic**
https://github.com/paypal/paypal-legal-components/blob/main/src/component.js

image

**Example Application:** 
https://pui-legal-app.herokuapp.com/

### CODE REVIEW

**Comment by westeezy** [comment]
awesome thanks @RatnadeepSimhadri. We can take a look soon

**Review by gregjopa — COMMENTED** [review]
@RatnadeepSimhadri ideally the package-lock.json file would only have one change with the new legal-components package. Can you try running `npm run flatten` locally to see if that minimizes the lock file changes?

**Comment by westeezy** [comment]
Hey @gregjopa, @wsbrunson and I were looking at this very briefly yesterday and it appears `grabthar add` is failing. From what I can tell that seems to be the way to add new packages here, but have you added in the past and seen that work or have you been doing the steps of: 1. add to `package.json` 2. `npm run flatten`?

**Comment by gregjopa** [comment]
> Hey @gregjopa, @wsbrunson and I were looking at this very briefly yesterday and it appears `grabthar add` is failing. From what I can tell that seems to be the way to add new packages here, but have you added in the past and seen that work or have you been doing the steps of: 1. add to `package.json` 2. `npm run flatten`?

I've actually never seen a new module added since I've been here. It does sound like `grabthar add` or `grabthar prune` may help. We will all have to figure this out together 😄

**Review by gregjopa — APPROVED** [review]
💯

**Pull request merged**
